model:
  name: SwinDepthT
  version: tiny
  embed_dim: 96
  depths: [2, 2, 6, 2]
  num_heads: [3, 6, 12, 24]
  window_size: 7

dataset:
  train: /path/to/training/data
  test: /path/to/testing/data

training:
  batch_size: 8
  epochs: 50
  lr: 0.0001
  weight_decay: 0.01
  save_path: weights/swin_tiny.pth

evaluation:
  weights_path: weights/swin_tiny.pth

device: cuda if torch.cuda.is_available() else 'cpu'
